#! /bin/bash
### Fetch research data from remote servers ###
# Construct an exclude.tmp list for rsync
cat > exclude.tmp <<EOF
oq#cq <--- this is an Rsync comment (I know, crazy eh?)
oq#cq Standard VASP big files
*WAVECAR*
*LOCPOT*
*XDATCAR*
oq#cq General unix core-dumps (crashed program memory contents)
*tar*
*tgz*
*core*
EOF
# Echo the contents to the user
echo "I am excluding from backup: "
cat exclude.tmp

#echo "Fetching work from TomTom"
#rsync -avzu -e "ssh -i $HOME/.ssh/curie_rsa" --exclude-from 'exclude.tmp' mmm0117@thomas.rc.ucl.ac.uk:/home/mmm0117/jobs/ ~/data

#echo "Fetching work from Balena"
#rsync -avzu --exclude-from 'exclude.tmp' lw827@balena.bath.ac.uk:/home/o/lw827/jobs/ ~/data/all 

#echo "Fetching work from Cobalt"
#rsync -avzu --exclude-from 'exclude.tmp' lucy@chpc-cobalt.bath.ac.uk:/home/lucy/jobs/ ~/data/all

#echo "Fetching work from Archerdot"
#rsync -avzu --exclude-from 'exclude.tmp' lucydot@login.archer.ac.uk:/work/e476/e476/lucydot/jobs/ ~/data/all

echo "Fetching work from Archer"
rsync -avzu --exclude-from 'exclude.tmp' lucy@login.archer.ac.uk:/work/e05/e05/lucy/jobs/ ~/data

#echo "Fetching work from Archerdotty"
#rsync -avzu --exclude-from 'exclude.tmp' dotty@login.archer.ac.uk:/work/e461/e461/dotty/jobs/ ~/data

#echo "Fetching work from Frisc"
#rsync -avzu --exclude-from 'exclude.tmp' pr1uycu1@login.archer.ac.uk:/work/pr1u1304/pr1u1304/pr1uycu1/jobs/ ~/data/all

#echo "Fetching work from Sisu"
#rsync -avzu -e "ssh -i $HOME/.ssh/curie_rsa" --exclude-from 'exclude.tmp' pr1uycul@sisu.csc.fi:/homeappl/home/pr1uycul/jobs/ ~/data

echo "Fetching work from cx1"
rsync -avzu --exclude-from 'exclude.tmp' lw3016@login.cx1.hpc.imperial.ac.uk:/work/lw3016/jobs/ ~/data

echo "Fetching work from daint"
rsync -avzu --exclude-from 'exclude.tmp' -e 'ssh -o "ProxyCommand ssh -Y lwhalley@ela.cscs.ch -W %h:%p"' lwhalley@daint.cscs.ch:/scratch/snx3000/lwhalley/jobs/ ~/data
