#!/bin/bash

FILE=$1

pdflatex $FILE.tex -interaction=nonstopmode
bibtex $FILE.aux
pdflatex $FILE.tex -interaction=nonstopmode
pdflatex $FILE.tex -interaction=nonstopmode

rm {*.log,*.aux,*.out,*.bbl,*.blg,*Notes.bib}
open $FILE.tex
