#! /bin/bash

################################################################################
#                                                                              #
# sendto: a shell script for syncronising folder to external servers           #
#                                                                              #
################################################################################

# Set flags to empty
directory= address= 
case $2 in 
    *) directory="/Users/lucydot/data/./$2"
        ;;
    esac
   # shift    # Shift arguments to examine next argument

case $1 in
    frisc) address="pr1uycu1@login.archer.ac.uk:/work/pr1u1304/pr1u1304/pr1uycu1/jobs"
        identity="~/.ssh/curie_rsa"
    ;;
    cobalt) address="lucy@chpc-cobalt.bath.ac.uk:/home/lucy/jobs/"
	   identity="~/.ssh/id_rsa"
    ;;
    archer) address="lucy@login.archer.ac.uk:/work/e05/e05/lucy/jobs/"
       identity="~/.ssh/curie_rsa"
    ;; 
    archerdot) address="lucydot@login.archer.ac.uk:/work/e476/e476/lucydot/jobs/"
               identity=".ssh/id_rsa"
    ;;
    sisu) address="pr1uycul@sisu.csc.fi:/homeappl/home/pr1uycul/jobs/"
          identity=".ssh/curie_rsa"
    ;;
    archerdotty) address="dotty@login.archer.ac.uk:/work/e461/e461/dotty/jobs/"
        identity=".ssh/curie_rsa"
        ;;
    cx1) address="lw3016@login.cx1.hpc.imperial.ac.uk:/work/lw3016/jobs/"
    ;;
    cx2) address="lw3016@login.cx2.hpc.imperial.ac.uk:/scratch/lw3016/jobs/"
    ;;
   
    tomtom) address="mmm0117@thomas.rc.ucl.ac.uk:/home/mmm0117/Scratch/" 
             identity=".ssh/curie_rsa"
    ;;
    bragg) address="lucydot@129.31.136.138:/home/lucydot/jobs/" 
    ;;
    daint) address="lwhalley@daint.cscs.ch:/users/lwhalley/jobs/"
    ;;
    esac  
########### Send files with rsync ##############
echo "Sending $directory to $address "
rsync -avzu --relative -e "ssh -i \"$HOME/$identity\""  "$directory" "$address"
