#! /usr/bin/env python


import numpy
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("vector", help="vector you want to find the length of", type=float, nargs=3)
parser.add_argument("-s", "--scale", help="scale each element of vector by given amount", type=float, nargs=1, action="store", dest="scale")
args = parser.parse_args()

if args.scale is not None:
    vector=numpy.asarray(args.vector)*args.scale[0]
   
else:
    vector=args.vector

print (numpy.sqrt((vector[0]**2)+(vector[1]**2)+(vector[2]**2))) 

